#!/usr/bin/env bash
#
# Rsync-based script for backups

error() {
  echo "ERROR: ${BASH_SOURCE[0]}: $1" >&2
  exit 1
}

usage() {
  local usage_string
  usage_string="Usage: rsync_backup OPTIONS
  OPTIONS
  -h                     Display this help message"
  echo "${usage_string}"
}

main() {
  if (( $# == 0 )); then
    usage
    error "${FUNCNAME[0]}: ${LINENO[0]}: at least one option required"
  fi

  while getopts :h opt; do
    case "${opt}" in
      h) usage; exit 0 ;;
      *) : ;;
    esac
  done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
