#!/usr/bin/env bash
#
# Rsync-based script for backups

error() {
  echo "ERROR: ${BASH_SOURCE[0]}: $1" >&2
  exit 1
}

main() {
  error "${FUNCNAME[0]}: ${LINENO[0]}: at least one option required"
}

main "$@"
